name: BrushPlugin
version: 1.0
main: pl.kwanek.brush.Brush
api-version: 1.18
commands:
  brush:
    description: Brush commands
    usage: /brush [give|timegive]
    permission: brush.use
    permission-message: You don't have permission to use this command.
